# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_Study_Week1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_Study_Week1

pod 'RxSwift', '6.1.0'
pod 'RxCocoa', '6.1.0'
end
