# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_1st_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_1st_Study

pod 'RxSwift', '6.1.0'
pod 'RxCocoa', '6.1.0'

end
